// Generated by CoffeeScript 2.3.0
var exts;

exts = ['.coffee', '.litcoffee', '.coffee.md'];

module.exports = function() {
  this.merge('exts', exts);
  this.merge('coffee.exts', exts);
  return this.worker('worker.js');
};
