// Generated by CoffeeScript 2.3.0
var COFFEE, log, path, semver;

semver = require('semver');

path = require('path');

log = require('lodge').debug('cush');

COFFEE = Symbol('coffeescript');

module.exports = function() {
  var exts;
  this.hook('package', function(pack) {
    var coffee, dep, deps, err, version;
    if (!(deps = pack.devDependencies)) {
      return;
    }
    if (!(version = deps['coffeescript'])) {
      return;
    }
    deps = path.join(pack.path, 'node_modules');
    try {
      dep = require.resolve(path.join(deps, 'coffeescript'));
    } catch (error) {
      err = error;
      // TODO: Try again when node_modules/coffeescript is added.
      log.warn(`'coffeescript' is not installed in '${deps}'`);
      return;
    }
    coffee = require(dep);
    if (semver.satisfies(coffee.VERSION, version)) {
      pack[COFFEE] = coffee;
      return;
    }
    return log.warn(`'coffeescript@${coffee.VERSION}' is installed, which does *not* satisfy ${version} from '${path.join(pack.path, 'package.json')}'`);
  });
  exts = this.get('coffee.exts');
  return this.transform(exts, (asset, pack) => {
    var coffee, result;
    if (!(coffee = pack[COFFEE])) {
      return;
    }
    result = coffee.compile(asset.content, {
      filename: this.relative(asset.path),
      sourceMap: true,
      bare: true
    });
    asset.ext = '.js';
    return {
      content: result.js,
      map: JSON.parse(result.v3SourceMap)
    };
  });
};
